services:
  - type: web
    name: vercel-server-bridge
    runtime: node
    rootDir: bridge
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: UPSTASH_URL
        sync: false
      - key: UPSTASH_TOKEN
        sync: false
